import { LocalDatabase, createUser, hashPassword } from "./src/core/storage.js";
import { CasinoEngine } from "./src/core/casino-engine.js";
import { createSlotGrid, evaluateSlot, theoreticalSlotRtp, SLOT_SYMBOLS, SLOT_PAYOUT_SCALE } from "./src/games/noir777.js";
import { spinRoulette, rouletteColor, settleRouletteBets, validateRouletteBet, ROULETTE_TYPES, ROULETTE_VARIANTS, theoreticalRouletteMetrics, simulateRouletteAsync } from "./src/games/roulette.js";
import { BlackjackTable, scoreHand } from "./src/games/blackjack.js";
import { DICE_BETS, rollDice, resolveDiceBet, baccaratRound, resolveBaccaratBet, createMinesBoard, minesMultiplier, generateCrashPoint } from "./src/games/instant-games.js";
import { NoirExperience } from "./src/presentation/experience.js";
import { RouletteWheelRenderer } from "./src/presentation/roulette-wheel.js";

const db = new LocalDatabase();
const engine = new CasinoEngine(db);
const app = document.querySelector("#app");
const modalRoot = document.querySelector("#modalRoot");
const experience = new NoirExperience(db.data.settings, () => db.save());
const debug = new URLSearchParams(location.search).get("debug") === "true";
let authMode = "login", lobbyCategory = "popular", currentGame = null, blackjack = null, blackjackRound = null;
let heroIndex = 0;
let rouletteBets = [], rouletteRenderer = null, selectedRouletteChip = 10000;
let minesRound = null, crashRound = null;

const GAMES = [
  { id:"slot", name:"NOIR 777", category:"slots", tag:"VOLATILIDAD ALTA", badge:"EXCLUSIVO", art:"7", color:"red", description:"20 líneas · Comodín · Dispersión" },
  { id:"roulette", name:"Ruleta Imperial", category:"table", tag:"RTP 97,30 %", badge:"POPULAR", art:"0", color:"green", description:"Europea o americana · Bola real" },
  { id:"blackjack", name:"Blackjack Élite", category:"table", tag:"6 MAZOS · PLANTA EN 17", badge:"MESA", art:"A♠", color:"blue", description:"Blackjack paga 3:2" },
  { id:"dice", name:"Dados Eléctricos", category:"originals", tag:"RTP 95,83 %", badge:"RÁPIDO", art:"••", color:"cyan", description:"Dos dados · Física 3D" },
  { id:"baccarat", name:"Baccarat Privé", category:"table", tag:"REGLAS CLÁSICAS", badge:"PRIVÉ", art:"B", color:"wine", description:"Jugador · Banca · Empate" },
  { id:"mines", name:"Minas NOIR", category:"originals", tag:"RIESGO CRECIENTE", badge:"NUEVO", art:"◆", color:"violet", description:"25 casillas · 3 minas" },
  { id:"crash", name:"Crash Volt", category:"originals", tag:"MULTIPLICADOR EN VIVO", badge:"EN VIVO", art:"×", color:"orange", description:"Retirá antes del impacto" },
];

const money = (value) => "Gs. " + Math.round(value).toLocaleString("es-PY");
const user = () => db.currentUser();
const escapeHtml = (value) => String(value).replace(/[&<>"]/g, (character) => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"})[character]);
const rankLabel = (rank) => ({GUEST:"INVITADO",PLAYER:"JUGADOR",SILVER:"PLATA",GOLD:"ORO",PLATINUM:"PLATINO",BLACK:"NEGRO",OBSIDIAN:"OBSIDIANA",CROWN:"CORONA"})[rank] || rank;
const icon = (name) => {
  const paths = {
    home:'<path d="M3 11 12 3l9 8v10h-6v-6H9v6H3Z"/>',
    search:'<circle cx="11" cy="11" r="7"/><path d="m16 16 5 5"/>',
    cards:'<rect x="4" y="3" width="13" height="17" rx="1"/><path d="m9 8 2-2 2 2-2 2Z"/><path d="m15 5 5 3v13H9"/>',
    star:'<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-3-5.6 3 1.1-6.2L3 9.6l6.2-.9Z"/>',
    profile:'<circle cx="12" cy="8" r="4"/><path d="M4 21c.8-5 3.5-7 8-7s7.2 2 8 7"/>',
    sound:'<path d="M4 10v4h4l5 4V6L8 10Z"/><path d="M17 9c1.8 1.7 1.8 4.3 0 6M20 6c3.5 3.3 3.5 8.7 0 12"/>',
    exit:'<path d="M14 8V4H4v16h10v-4M10 12h11m-4-4 4 4-4 4"/>',
    grid:'<path d="M4 4h6v6H4Zm10 0h6v6h-6ZM4 14h6v6H4Zm10 0h6v6h-6Z"/>',
  };
  return `<svg viewBox="0 0 24 24" aria-hidden="true">${paths[name] || paths.grid}</svg>`;
};

function route() {
  const path = location.hash.slice(1) || (user() ? "/lobby" : "/");
  closeModal();
  window.scrollTo(0, 0);
  experience.setScene(path.startsWith("/game/") ? path.split("/").at(-1) : path === "/lobby" ? "lobby" : "landing");
  if (path === "/admin") return renderAdmin();
  if (path.startsWith("/game/")) return user() ? renderGame(path.split("/").at(-1)) : go("/auth");
  if (path === "/profile") return user() ? renderProfile() : go("/auth");
  if (path === "/auth") return renderAuth();
  if (path === "/lobby") return user() ? renderLobby() : go("/auth");
  renderLanding();
}

function go(path) {
  const destination = path.split("?")[0];
  const accent = destination.includes("slot") ? "magenta" : destination.includes("roulette") ? "green" : destination.includes("blackjack") ? "cream" : "gold";
  experience.transition(() => { window.scrollTo(0, 0); if (location.hash === "#" + destination) route(); else location.hash = destination; }, accent);
}

function renderLanding() {
  app.innerHTML = `<main class="landing nocturne">
    <nav class="public-nav"><a class="wordmark" href="#/">NOIR<span>CASINO</span></a><div class="public-links"><a href="#games">SALA DE JUEGOS</a><a href="#jackpots">PREMIOS</a><a href="#vip">PRIVÉ</a></div><div class="nav-actions"><button id="publicSound" class="sound-orb" aria-label="Sonido">${icon("sound")}</button><button data-go="/auth" class="text-button">INGRESAR</button><button data-auth="register" class="gold-button small">CREAR MEMBRESÍA</button></div></nav>
    <section class="hero hero-cinematic">
      <div class="hero-aura" data-parallax="-10"></div><div class="laser laser-one"></div><div class="laser laser-two"></div>
      <div class="hero-copy" data-parallax="6"><p class="overline"><i></i> CLUB DIGITAL PRIVADO · ASUNCIÓN</p><h1><span>NOIR</span><em>CASINO</em></h1><p class="hero-lead">La noche tiene una mesa reservada para vos.</p><div class="hero-bonus"><small>FORTUNA DE BIENVENIDA</small><strong>${money(500000)}</strong><span>VIRTUALES · 20 GIROS GRATIS</span></div><button data-auth="register" class="play-cta"><span>ENTRAR AL CASINO</span><b>→</b></button><small class="legal-whisper">ENTRETENIMIENTO VIRTUAL · SIN VALOR MONETARIO REAL</small></div>
      <div class="casino-diorama" aria-hidden="true" data-parallax="18">
        <div class="wheel-shadow"></div><div class="hero-wheel"><div class="wheel-rim"><div class="wheel-numbers">${[0,32,15,19,4,21,2,25,17,34,6,27].map((number,index)=>`<i style="--n:${index}">${number}</i>`).join("")}</div><div class="wheel-bowl"><span></span><b>N</b></div></div><i class="hero-ball"></i></div>
        <div class="hero-slot"><header>NOIR <i>777</i></header><div><b>7</b><b>W</b><b>7</b></div><footer>MEGA</footer></div>
        <div class="floating-card card-ace"><b>A</b><i>♠</i></div><div class="floating-card card-king"><b>K</b><i>♦</i></div>
        <div class="floating-chip chip-one"><span>N</span></div><div class="floating-chip chip-two"><span>500</span></div><div class="floating-chip chip-three"><span>VIP</span></div>
      </div>
      <div class="hero-jackpot" id="jackpots"><span>PREMIO MAYOR</span><strong data-live-jackpot data-value="${experience.currentJackpot}">${money(experience.currentJackpot)}</strong><i>PROGRESIVO EN VIVO</i></div>
      <div class="scroll-cue"><i></i><span>BAJAR A LA SALA</span></div>
    </section>
    <section class="jackpot-gallery"><p class="overline">BÓVEDAS EN VIVO</p><div><article><span>MINI</span><strong>${money(8412900)}</strong><i></i></article><article><span>MAYOR</span><strong>${money(96831200)}</strong><i></i></article><article class="mega"><span>MEGA</span><strong data-live-jackpot data-value="${experience.currentJackpot}">${money(experience.currentJackpot)}</strong><i></i></article></div></section>
    <section class="featured" id="games"><header><div><p class="overline">COLECCIÓN NOIR</p><h2>ELEGÍ TU NOCHE</h2></div><button data-go="/auth" class="text-button">ENTRAR A LA SALA →</button></header><div class="public-game-grid">${GAMES.map(gameCard).join("")}</div></section>
    <section class="vip-gate" id="vip"><div class="vip-doors"><i></i><b>N</b><i></i></div><div><p class="overline">SALA OBSIDIANA</p><h2>PRIVILEGIOS<br>FUERA DE SERIE</h2><p>Un espacio reservado para rangos altos, límites especiales y recompensas ceremoniales.</p><button data-auth="register" class="light-button">SOLICITAR MEMBRESÍA →</button></div></section>
    <footer class="public-footer"><span>NOIR CASINO · 2026</span><p>Experiencia ficticia. No acepta depósitos, retiros ni dinero real.</p></footer>
  </main>`;
  bindCommon();
  experience.bindParallax(app);
  document.querySelector("#publicSound").onclick = () => experience.openAudioPanel(modalRoot);
  document.querySelectorAll("[data-game]").forEach((button) => button.onclick = () => { authMode = "register"; go("/auth"); });
}

function renderAuth() {
  app.innerHTML = `<main class="auth-page auth-cinematic"><section class="auth-brand"><a class="wordmark" href="#/">NOIR<span>CASINO</span></a><div class="auth-stage" data-parallax="14"><div class="auth-wheel"><i></i><b>N</b></div><div class="auth-chip chip-a">500</div><div class="auth-chip chip-b">VIP</div><div class="auth-card"><b>A</b><span>♠</span></div></div><div class="auth-message"><p class="overline">SÓLO MIEMBROS</p><h1>TU NOCHE<br>EMPIEZA <i>ACÁ</i></h1><p>Entrá a una sala construida para el juego, la precisión y la atmósfera.</p></div><small>SALDO VIRTUAL — SIN VALOR MONETARIO REAL</small></section><section class="auth-panel"><button class="auth-close" data-go="/">×</button><button id="authSound" class="auth-sound" aria-label="Configuración de sonido">${icon("sound")}</button><div class="auth-tabs"><button data-mode="login" class="${authMode==="login"?"active":""}">INGRESAR</button><button data-mode="register" class="${authMode==="register"?"active":""}">MEMBRESÍA</button></div>${authMode === "register" ? registerForm() : authMode === "reset" ? resetForm() : loginForm()}</section></main>`;
  bindCommon();
  experience.bindParallax(app);
  document.querySelector("#authSound").onclick = () => experience.openAudioPanel(modalRoot);
  document.querySelectorAll("[data-mode]").forEach((button) => button.onclick = () => { authMode = button.dataset.mode; renderAuth(); });
  document.querySelector("#authForm")?.addEventListener("submit", handleAuth);
}

const loginForm = () => `<form id="authForm" class="auth-form"><p class="overline">BIENVENIDO DE NUEVO</p><h2>Volvé a la sala.</h2><label><span>Email o usuario</span><input name="identity" autocomplete="username" required></label><label><span>Contraseña</span><input type="password" name="password" autocomplete="current-password" minlength="6" required></label><button class="gold-button" type="submit">DESBLOQUEAR NOIR <b>→</b></button><button class="link-button" type="button" data-mode="reset">RECUPERAR ACCESO LOCAL</button><p class="form-note">La membresía vive en este dispositivo. Sin dinero real.</p></form>`;
const registerForm = () => `<form id="authForm" class="auth-form"><p class="overline">CREAR MEMBRESÍA</p><h2>Reclamá tu lugar.</h2><div class="form-row"><label><span>Usuario</span><input name="username" minlength="3" maxlength="18" required></label><label><span>Iniciales</span><input name="avatar" maxlength="2" placeholder="NV"></label></div><label><span>Email</span><input type="email" name="email" autocomplete="email" required></label><label><span>Contraseña</span><input type="password" name="password" minlength="6" autocomplete="new-password" required></label><label><span>Confirmar contraseña</span><input type="password" name="confirm" minlength="6" required></label><div class="membership-ticket"><span>FORTUNA DE BIENVENIDA</span><strong>${money(500000)}</strong><i>+ 20 GIROS GRATIS</i></div><button class="gold-button" type="submit">CREAR MEMBRESÍA <b>→</b></button></form>`;
const resetForm = () => `<form id="authForm" class="auth-form"><p class="overline">RECUPERACIÓN LOCAL</p><h2>Recuperación simulada.</h2><label>Email<input type="email" name="email" required></label><button class="gold-button" type="submit">GENERAR AVISO LOCAL</button><button class="link-button" type="button" data-mode="login">VOLVER</button><p class="form-note">Sin backend no se envía ningún correo real.</p></form>`;

async function handleAuth(event) {
  event.preventDefault(); const data = Object.fromEntries(new FormData(event.currentTarget));
  if (authMode === "reset") { toast("RECUPERACIÓN SIMULADA", "En una versión con backend recibirías un correo seguro."); authMode = "login"; return renderAuth(); }
  const passwordHash = await hashPassword(data.password);
  if (authMode === "register") {
    if (data.password !== data.confirm) return toast("CONTRASEÑAS DIFERENTES", "Revisá la confirmación.", true);
    if (db.data.users.some((item) => item.email === data.email.toLowerCase() || item.username.toLowerCase() === data.username.toLowerCase())) return toast("CUENTA EXISTENTE", "Usá otro email o usuario.", true);
    const created = createUser({ username:data.username, email:data.email, passwordHash, avatar:data.avatar || data.username[0] }); db.data.users.push(created); db.data.sessionUserId = created.id; db.save(); toast("BIENVENIDO A NOIR", `${money(500000)} y 20 giros gratis acreditados.`); go("/lobby"); setTimeout(()=>experience.winCelebration(500000, 20), 900);
  } else {
    const found = db.data.users.find((item) => (item.email === data.identity.toLowerCase() || item.username.toLowerCase() === data.identity.toLowerCase()) && item.passwordHash === passwordHash);
    if (!found) return toast("ACCESO DENEGADO", "Usuario o contraseña incorrectos.", true);
    db.data.sessionUserId = found.id; db.save(); go("/lobby");
  }
}

function shell(content, active = "home") {
  const current = user();
  return `<div class="casino-shell"><header class="casino-header"><a class="wordmark" href="#/lobby">NOIR<span>CASINO</span></a><label class="search-box">${icon("search")}<input id="gameSearch" placeholder="Buscar juegos" aria-label="Buscar juegos"></label><div class="live-status"><i></i> SALA EN VIVO</div><button class="audio-button" id="audioButton" aria-label="Configuración de sonido">${icon("sound")}</button><button class="wallet-pill" id="walletButton" aria-label="Abrir saldo virtual"><span data-value="${current.balance}">${money(current.balance)}</span><small>SALDO VIRTUAL</small></button><button class="notice-button" id="noticeButton" aria-label="Abrir notificaciones"><i></i><b>${current.notifications.filter(n=>!n.read).length}</b></button><button class="profile-chip" data-go="/profile" aria-label="Abrir perfil"><i>${escapeHtml(current.avatar)}</i><span>${escapeHtml(current.username)}<small>NIVEL ${current.level} · ${rankLabel(current.rank)}</small></span></button></header><aside class="side-nav" aria-label="Navegación principal">${navItem("home","home","CASINO","/lobby",active)}${navItem("slots","grid","TRAGAMONEDAS","/lobby?cat=slots",active)}${navItem("table","cards","JUEGOS DE MESA","/lobby?cat=table",active)}${navItem("favorite","star","FAVORITOS","/lobby?cat=favorites",active)}${navItem("profile","profile","PERFIL","/profile",active)}<div class="side-spacer"></div><button id="rewardsButton">${icon("star")} RECOMPENSAS</button><button id="adminLink">${icon("grid")} ADMINISTRACIÓN</button><button id="logoutButton">${icon("exit")} SALIR</button></aside><main class="casino-main">${content}</main><nav class="mobile-nav" aria-label="Navegación móvil">${navItem("home","home","INICIO","/lobby",active)}${navItem("slots","search","BUSCAR","/lobby",active)}${navItem("table","grid","JUEGOS","/lobby",active)}<button id="mobileRewards">${icon("star")}PREMIOS</button>${navItem("profile","profile","PERFIL","/profile",active)}</nav></div>`;
}

const navItem = (id, iconName, label, path, active) => `<button data-go="${path}" class="${active===id?"active":""}">${icon(iconName)}${label}</button>`;

function renderLobby() {
  const current = user();
  const hero = [{eyebrow:"LA SALA ESTÁ ABIERTA",title:"NOIR 777",copy:"20 líneas. Energía salvaje. Una noche progresiva.",tone:"mega"},{eyebrow:"FORTUNA DE MEMBRESÍA",title:"20 GIROS GRATIS",copy:"Tu ritual de bienvenida te espera dentro de la máquina.",tone:"welcome"},{eyebrow:"NOCHE DE RULETA",title:"2X XP",copy:"Precisión europea bajo luces esmeralda.",tone:"roulette"}][heroIndex%3];
  const filtered = GAMES.filter((game) => lobbyCategory === "popular" || game.category === lobbyCategory || (lobbyCategory === "favorites" && current.favorites.includes(game.id)) || (lobbyCategory === "recent" && current.recent.includes(game.id)));
  app.innerHTML = shell(`<section class="lobby-page">
    <div class="casino-hero ${hero.tone}" data-parallax="5"><img class="hero-scene-img" src="./assets/noir-lobby-scene.svg" width="1600" height="900" alt="Ilustración original de una sala NOIR con ruleta, fichas, cartas y tragamonedas" fetchpriority="high"><div class="hero-copy-lobby"><p class="overline">${hero.eyebrow}</p><h1>${hero.title}</h1><p>${hero.copy}</p><div class="hero-proof"><span>ASUNCIÓN</span><span>7 JUEGOS ORIGINALES</span><span>SALDO VIRTUAL</span></div><button class="light-button" data-game="${hero.tone==="roulette"?"roulette":"slot"}">JUGAR DESTACADO <b>→</b></button></div><div class="hero-dots">${[0,1,2].map(i=>`<button aria-label="Promoción ${i+1}" data-hero="${i}" class="${heroIndex===i?"active":""}"></button>`).join("")}</div></div>
    <section class="live-jackpots"><div class="jackpot-title"><i></i><span>PREMIOS EN VIVO</span></div><article><span>MINI</span><strong>${money(db.data.jackpot.mini)}</strong></article><article><span>MAYOR</span><strong>${money(db.data.jackpot.major)}</strong></article><article class="mega"><span>MEGA</span><strong data-live-jackpot data-value="${experience.currentJackpot}">${money(experience.currentJackpot)}</strong></article><div class="ticker"><span>GANANCIA RECIENTE · NIGHTOWL · ${money(1850000)}</span></div></section>
    <section class="featured-floor"><div class="section-heading"><div><p class="overline">EXPERIENCIA DESTACADA</p><h2>JUEGO PRINCIPAL</h2></div><span>EN VIVO · VOLATILIDAD ALTA</span></div><article class="featured-game"><div class="featured-art"><div class="seven-monolith">7</div><div class="reel-rings"><i></i><i></i><i></i></div><div class="coin-rain">${Array.from({length:12},(_,i)=>`<i style="--i:${i}"></i>`).join("")}</div></div><div class="featured-copy"><span>ORIGINAL NOIR</span><h3>NOIR<br><i>777</i></h3><p>Entrá a una máquina física de cinco rodillos, símbolos premium y premios de hasta 1.500×.</p><div><b>RTP ${(theoreticalSlotRtp()*100).toFixed(2).replace(".",",")}%</b><b>20 LÍNEAS</b><b>GIROS GRATIS</b></div><button data-game="slot" class="play-cta"><span>ENTRAR A LA MÁQUINA</span><b>→</b></button></div></article></section>
    <section class="collection-floor"><div class="section-heading"><div><p class="overline">POPULARES AHORA</p><h2>ELEGÍ TU JUEGO</h2></div><div class="category-tabs" role="tablist">${[["popular","TODOS"],["favorites","FAVORITOS"],["recent","RECIENTES"],["slots","TRAGAMONEDAS"],["table","MESAS"],["originals","ORIGINALES"]].map(([id,label])=>`<button role="tab" aria-selected="${lobbyCategory===id}" data-category="${id}" class="${lobbyCategory===id?"active":""}">${label}</button>`).join("")}</div></div><div class="game-grid" id="gameGrid">${filtered.length?filtered.map(gameCard).join(""):`<div class="empty-state"><i>N</i><b>LA COLECCIÓN ESTÁ VACÍA</b><span>Jugá o marcá favoritos para construir tu colección privada.</span><button data-category="popular">VER TODOS LOS JUEGOS</button></div>`}</div></section>
    <section class="balance-strip"><div><span>SALDO VIRTUAL</span><strong>${money(current.balance)}</strong></div><div><span>NIVEL DE MIEMBRO</span><strong>${current.level} · ${rankLabel(current.rank)}</strong></div><div><span>EXPERIENCIA</span><strong>${current.xp.toLocaleString("es-PY")} XP</strong></div><div><span>GIROS GRATIS</span><strong>${current.freeSpins}</strong></div><button id="claimCredits">OBTENER CRÉDITOS DE PRUEBA</button></section>
    <section class="lobby-lower"><article><div class="rank-orbit"><b>${current.level}</b><i></i></div><div><p class="overline">TU ASCENSO</p><h3>CAMINO A ${current.rank==="GUEST"?"JUGADOR":"PLATA"}</h3><div class="progress"><i style="width:${Math.min(100,current.xp%250/2.5)}%"></i></div><span>${current.xp%250} / 250 XP</span></div></article><article><p class="overline">ÚLTIMA MESA</p><h3>${current.history[0]?`${GAMES.find(game=>game.id===current.history[0].game)?.name||current.history[0].game} · ${money(current.history[0].net)}`:"TU HISTORIAL EMPIEZA ESTA NOCHE"}</h3><button data-go="/profile" class="text-button">ABRIR PERFIL →</button></article></section></section>`, "home");
  bindShell(); bindGameCards();
  experience.bindParallax(app);
  document.querySelectorAll("[data-category]").forEach(button=>button.onclick=()=>{lobbyCategory=button.dataset.category;renderLobby();});
  document.querySelectorAll("[data-hero]").forEach(button=>button.onclick=()=>{heroIndex=Number(button.dataset.hero);renderLobby();});
  document.querySelector("#claimCredits").onclick = claimCredits;
}

function gameCard(game) {
  const current = user(); const favorite = current?.favorites.includes(game.id);
  const art = {
    slot:`<div class="cover-machine"><i></i><div><b>7</b><b>W</b><b>7</b></div><span>PREMIO</span></div>`,
    roulette:`<div class="cover-wheel"><i></i><b>0</b><span></span></div>`,
    blackjack:`<div class="cover-table"><i class="card-a"><b>A</b><span>♠</span></i><i class="card-k"><b>K</b><span>♦</span></i><em></em></div>`,
    baccarat:`<div class="cover-table cover-baccarat"><i class="card-a"><b>9</b><span>♥</span></i><i class="card-k"><b>8</b><span>♣</span></i><em></em></div>`,
    dice:`<div class="cover-dice"><i><b>••</b><span>•••</span></i><i><b>•••</b><span>••</span></i></div>`,
    mines:`<div class="cover-mines">${Array.from({length:9},(_,index)=>`<i class="${index===4?"gem":""}"><b>${index===4?"◆":""}</b></i>`).join("")}</div>`,
    crash:`<div class="cover-crash"><strong>4.72×</strong><i></i><span></span></div>`,
  }[game.id];
  return `<article class="game-card game-${game.id}" data-card="${game.id}" data-name="${game.name.toLowerCase()}" data-parallax="3" role="button" tabindex="0" aria-label="Jugar ${game.name}"><div class="game-art ${game.color}"><div class="card-beam"></div><span class="game-badge">${game.badge}</span>${art}<span class="card-index">${game.art}</span>${current?`<button class="favorite ${favorite?"active":""}" data-favorite="${game.id}" aria-label="${favorite?"Quitar de":"Añadir a"} favoritos">${favorite?"★":"☆"}</button>`:""}<button class="card-play" data-game="${game.id}"><span>JUGAR</span> →</button></div><div class="game-info"><div><b>${game.name}</b><span>${game.description}</span></div><small>${game.tag}</small></div></article>`;
}

function bindGameCards() {
  document.querySelectorAll("[data-game]").forEach(button=>button.onclick=(event)=>{event.stopPropagation();go("/game/"+button.dataset.game);});
  document.querySelectorAll("[data-favorite]").forEach(button=>button.onclick=(event)=>{event.stopPropagation();const current=user(),id=button.dataset.favorite;current.favorites=current.favorites.includes(id)?current.favorites.filter(item=>item!==id):[...current.favorites,id];db.save();renderLobby();});
  document.querySelectorAll("[data-card]").forEach(card=>{card.onclick=event=>{if(event.target.closest("button"))return;go("/game/"+card.dataset.card);};card.onkeydown=event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();go("/game/"+card.dataset.card);}};});
  document.querySelector("#gameSearch")?.addEventListener("input",event=>document.querySelectorAll("[data-card]").forEach(card=>card.hidden=!card.dataset.name.includes(event.target.value.toLowerCase())));
}

function renderGame(id) {
  if (!GAMES.some(game=>game.id===id)) return go("/lobby");
  rouletteRenderer?.destroy(); rouletteRenderer=null; currentGame=id;
  const views={slot:slotView,roulette:rouletteView,blackjack:blackjackView,dice:diceView,baccarat:baccaratView,mines:minesView,crash:crashView};
  const game=GAMES.find(item=>item.id===id),body=views[id]();
  app.innerHTML = shell(`<section class="game-page game-scene-${id}"><header class="game-page-head"><button class="back-casino" data-go="/lobby">← VOLVER A LA SALA</button><div><p class="overline">${game.tag}</p><h1>${game.name}</h1></div><span><i></i> JUEGO VIRTUAL</span></header>${body}${debug?debugPanel():""}</section>`, id==="slot"?"slots":"table"); bindShell(); bindGame(id);
}

function betOptions(max = 250000) { return [1000,5000,10000,25000,50000,100000,250000].filter(v=>v<=max).map(v=>`<option value="${v}">${money(v)}</option>`).join(""); }

function slotView() {
  return `<div class="slot-chamber"><div class="slot-ambient-lights"><i></i><i></i></div><div class="slot-stage"><div class="slot-topper"><div><span>MINI</span><strong>${money(db.data.jackpot.mini)}</strong></div><div class="slot-marquee"><small>ORIGINAL NOIR</small><strong>NOIR <i>777</i></strong><span>FORTUNA EN LA OSCURIDAD</span></div><div><span>MEGA</span><strong data-live-jackpot data-value="${experience.currentJackpot}">${money(experience.currentJackpot)}</strong></div></div><div class="slot-cabinet"><div class="cabinet-lights left"></div><div class="slot-glass"><div class="reel-header"><span>20 LÍNEAS</span><i>EL COMODÍN PAGA EN AMBOS SENTIDOS</i><span>RTP ${(theoreticalSlotRtp()*100).toFixed(2).replace(".",",")}%</span></div><div class="slot-window" id="slotGrid">${Array.from({length:15},(_,i)=>`<i class="slot-symbol ghost" style="--delay:${i*35}ms"><b>N</b><span>NOIR</span></i>`).join("")}</div><div class="win-line"></div><div class="game-message" id="gameMessage">ELEGÍ TU APUESTA</div></div><div class="cabinet-lights right"></div></div><div class="game-controls"><label><span>APUESTA</span><select id="gameBet">${betOptions()}</select></label><div class="control-meter"><span>GANANCIA</span><strong id="slotWin">${money(0)}</strong></div><div class="spin-housing"><i></i><button id="slotSpin" class="physical-spin"><span>GIRAR</span><small>PRESIONAR</small></button></div><div><span>GIROS GRATIS</span><strong id="freeSpinCount">${user().freeSpins}</strong></div></div><button class="paytable-link" id="paytableButton">ABRIR TABLA DE PAGOS <b>+</b></button></div></div>`;
}

function rouletteView() {
  const variant=db.data.games.roulette.variant||"european",metrics=theoreticalRouletteMetrics(variant);
  return `<div class="roulette-room roulette-${variant}"><section class="roulette-status"><div><span>VARIANTE</span><strong>${ROULETTE_VARIANTS[variant].label.toUpperCase()}</strong></div><div><span>RTP TEÓRICO</span><strong>${(metrics.rtp*100).toFixed(2).replace(".",",")}%</strong></div><div><span>VENTAJA DE LA CASA</span><strong>${(metrics.houseEdge*100).toFixed(2).replace(".",",")}%</strong></div><div class="roulette-result-display"><span>NÚMERO GANADOR</span><strong id="rouletteResult">—</strong></div></section><div class="roulette-layout roulette-canvas-layout"><div class="roulette-wheel-wrap"><div class="wheel-halo"></div><canvas id="rouletteCanvas" aria-label="Ruleta animada"></canvas><div class="roulette-camera-flash"></div><div class="roulette-history" id="rouletteHistory">LA RULETA ESTÁ LISTA</div></div><div class="roulette-table roulette-betting"><div class="table-rail"></div><p class="overline">RULETA ${ROULETTE_VARIANTS[variant].label.toUpperCase()}</p><h2>COLOCÁ TUS FICHAS</h2><div class="roulette-board" id="rouletteBoard">${rouletteBoard(variant)}</div><div class="physical-chips">${[1000,5000,10000,25000,50000,100000].map((value,index)=>`<button data-chip="${value}" class="${value===selectedRouletteChip?"active":""}" style="--chip:${index}"><i>${value/1000}K</i></button>`).join("")}</div><div class="manual-roulette-bet"><label><span>APUESTA ESPECIAL</span><select id="rouletteType">${Object.entries(ROULETTE_TYPES).filter(([,config])=>config.count).map(([id,config])=>`<option value="${id}">${config.label} · ${config.profitOdds}:1</option>`).join("")}</select></label><label><span>NÚMEROS</span><input id="rouletteTarget" value="7" placeholder="Ej.: 7 o 7,8"></label><button id="rouletteAdd">AÑADIR</button></div><div class="roulette-slip"><header><span>APUESTAS DE LA RONDA</span><button id="rouletteClear">LIMPIAR</button></header><div id="rouletteSlip">${rouletteSlipHtml()}</div><footer><span>TOTAL</span><strong id="rouletteStake">${money(rouletteBets.reduce((sum,bet)=>sum+bet.amount,0))}</strong></footer></div><button class="roulette-spin-control" id="rouletteSpin" ${rouletteBets.length?"":"disabled"}><i></i><span>GIRAR RULETA</span></button></div></div></div>`;
}

function rouletteBoard(variant){
  const zero=`<button class="number green zero" data-board-type="straight" data-board-target="0">0</button>${variant==="american"?`<button class="number green double-zero" data-board-type="straight" data-board-target="00">00</button>`:""}`;
  const numbers=Array.from({length:36},(_,index)=>index+1).map(number=>`<button class="number ${rouletteColor(number)}" data-board-type="straight" data-board-target="${number}">${number}</button>`).join("");
  const outside=[["low","1–18"],["even","PAR"],["red","ROJO"],["black","NEGRO"],["odd","IMPAR"],["high","19–36"],["dozen1","1.ª DOCENA"],["dozen2","2.ª DOCENA"],["dozen3","3.ª DOCENA"],["column1","1.ª COLUMNA"],["column2","2.ª COLUMNA"],["column3","3.ª COLUMNA"]].map(([type,label])=>`<button class="outside ${type}" data-board-type="${type}" data-board-target="">${label}</button>`).join("");
  return `<div class="zero-column">${zero}</div><div class="number-grid">${numbers}</div><div class="outside-grid">${outside}</div>`;
}

function rouletteSlipHtml(){return rouletteBets.length?rouletteBets.map((bet,index)=>`<article data-slip="${index}"><i class="chip-dot"></i><span>${ROULETTE_TYPES[bet.type].label}${bet.target!==""?` · ${bet.target}`:""}</span><strong>${money(bet.amount)}</strong><button data-remove-bet="${index}">×</button></article>`).join(""):`<p>Elegí una ficha y tocá el tablero.</p>`;}

function blackjackView() {
  return `<div class="blackjack-room"><div class="dealer-silhouette"><i></i><span>CRUPIER NOIR</span></div><div class="deck-stack"><i></i><i></i><i></i></div><div class="blackjack-table"><div class="felt-lines"></div><div class="dealer-zone"><p>CRUPIER <span id="dealerScore"></span></p><div class="cards" id="dealerCards"><i class="card back-card">N</i><i class="card back-card">N</i></div></div><div class="table-mark"><b>NOIR</b><span>BLACKJACK</span><small>BLACKJACK PAGA 3 A 2 · EL CRUPIER SE PLANTA EN 17 SUAVE</small></div><div class="player-zone"><div class="cards waiting-hand" id="playerCards"><span>COLOCÁ TU APUESTA</span></div><p>JUGADOR <span id="playerScore"></span></p></div><div class="betting-spot"><i></i><span>ZONA DE APUESTA</span></div><div class="blackjack-chips" aria-label="Fichas de apuesta">${[1000,5000,10000,25000,50000,100000].map((value,index)=>`<button aria-label="Ficha ${money(value)}" data-blackjack-chip="${value}" style="--chip:${index}"><i>${value/1000}K</i></button>`).join("")}</div><div class="blackjack-controls"><label><span>VALOR DE FICHA</span><select id="gameBet">${betOptions(500000)}</select></label><button class="deal-control" id="blackjackDeal">REPARTIR</button><button id="blackjackHit" disabled>PEDIR CARTA</button><button id="blackjackStand" disabled>PLANTARSE</button><button id="blackjackDouble" disabled>DUPLICAR</button><button id="blackjackSplit" disabled>DIVIDIR</button><button id="blackjackInsurance" disabled>SEGURO</button></div><div class="game-message" id="gameMessage">LA MESA ESTÁ ABIERTA</div></div></div>`;
}

function diceView(){return `<div class="dice-room"><div class="dice-lights"><i></i><i></i></div><section class="dice-arena"><p class="overline">DADOS NOIR · VENTAJA 4,17 %</p><h2>LANZAMIENTO ELÉCTRICO</h2><div class="dice-stage" id="diceStage"><div class="die die-one" data-face="1">${dieFaces()}</div><div class="die die-two" data-face="1">${dieFaces()}</div><div class="dice-impact"></div></div><div class="dice-total"><span>RESULTADO</span><strong id="diceTotal">—</strong></div><div class="dice-controls"><label><span>APUESTA</span><select id="gameBet">${betOptions()}</select></label><div class="dice-bets">${Object.entries(DICE_BETS).map(([id,config])=>`<button data-dice-bet="${id}" class="${id==="under7"?"active":""}">${config.label}<small>${(config.returnMultiplier-1).toFixed(2)}:1</small></button>`).join("")}</div><button id="diceRoll" class="dice-roll-button">LANZAR DADOS</button></div><div class="game-message" id="gameMessage">ELEGÍ UN RESULTADO</div></section></div>`;}
const dieFaces=()=>Array.from({length:6},(_,index)=>`<i class="face face-${index+1}">${Array.from({length:index+1},()=>"<b></b>").join("")}</i>`).join("");

function baccaratView(){return `<div class="baccarat-room"><section class="baccarat-table"><div class="baccarat-aura"></div><p class="overline">BACCARAT CLÁSICO</p><div class="baccarat-hands"><article><h3>JUGADOR <span id="baccaratPlayerScore">—</span></h3><div class="cards" id="baccaratPlayer"><i class="card back-card">N</i><i class="card back-card">N</i></div></article><div class="baccarat-mark"><b>N</b><span>PRIVÉ</span></div><article><h3>BANCA <span id="baccaratBankerScore">—</span></h3><div class="cards" id="baccaratBanker"><i class="card back-card">N</i><i class="card back-card">N</i></div></article></div><div class="baccarat-controls"><label><span>APUESTA</span><select id="gameBet">${betOptions(500000)}</select></label>${[["player","JUGADOR · 1:1"],["banker","BANCA · 0,95:1"],["tie","EMPATE · 8:1"]].map(([id,label])=>`<button data-baccarat-bet="${id}" class="${id==="player"?"active":""}">${label}</button>`).join("")}<button id="baccaratDeal" class="deal-control">REPARTIR</button></div><div class="game-message" id="gameMessage">ELEGÍ JUGADOR, BANCA O EMPATE</div></section></div>`;}

function minesView(){return `<div class="mines-room"><section class="mines-console"><header><div><p class="overline">MINAS NOIR</p><h2>CÁMARA DE GEMAS</h2></div><div class="mines-multiplier"><span>MULTIPLICADOR</span><strong id="minesMultiplier">1.00×</strong></div></header><div class="mines-board" id="minesBoard">${Array.from({length:25},(_,index)=>`<button data-mine-cell="${index}"><i></i><span></span></button>`).join("")}</div><div class="mines-controls"><label><span>APUESTA</span><select id="gameBet">${betOptions()}</select></label><div><span>MINAS</span><strong>3</strong></div><button id="minesStart" class="mines-start">INICIAR RONDA</button><button id="minesCashout" disabled>RETIRAR</button></div><div class="game-message" id="gameMessage">INICIÁ UNA RONDA PARA ABRIR LA BÓVEDA</div></section></div>`;}

function crashView(){return `<div class="crash-room"><section class="crash-arena"><canvas id="crashCanvas"></canvas><div class="crash-speedlines"></div><div class="crash-value"><span>MULTIPLICADOR</span><strong id="crashMultiplier">1.00×</strong><i id="crashStatus">ESPERANDO APUESTA</i></div><div class="crash-ship"><i></i><b>N</b></div><div class="crash-controls"><label><span>APUESTA</span><select id="gameBet">${betOptions()}</select></label><button id="crashStart">INICIAR</button><button id="crashCashout" disabled>RETIRAR</button></div><div class="game-message" id="gameMessage">RETIRÁ ANTES DEL IMPACTO</div></section></div>`;}

function bindGame(id) {
  if (id === "slot") { document.querySelector("#slotSpin").onclick=playSlot; document.querySelector("#paytableButton").onclick=showPaytable; }
  if (id === "roulette") bindRoulette();
  if (id === "blackjack") bindBlackjack();
  if (id === "dice") bindDice();
  if (id === "baccarat") bindBaccarat();
  if (id === "mines") bindMines();
  if (id === "crash") bindCrash();
}

async function playSlot() {
  const button=document.querySelector("#slotSpin"), amount=Number(document.querySelector("#gameBet").value), current=user();
  const free=current.freeSpins>0; let round;
  try { round=engine.beginRound(current,"slot",free?db.data.games.slot.minBet:amount,{freeSpin:free}); if(free){current.balance+=db.data.games.slot.minBet;round.bet=amount;current.freeSpins-=1;} }
  catch(error){return toast("NO SE PUDO GIRAR",error.message,true);}
  const grid=createSlotGrid(),outcome=evaluateSlot(grid,amount),anticipation=grid.slice(0,4).flat().filter(symbol=>symbol.id==="SCATTER").length>=2;
  experience.audio.play("spin");button.disabled=true;document.querySelector(".slot-stage").classList.add("machine-active");document.querySelector("#gameMessage").textContent=free?`GIRO GRATIS · ${current.freeSpins} RESTANTES`:"RODILLOS A MÁXIMA VELOCIDAD";
  const nodes=[...document.querySelectorAll(".slot-symbol")];nodes.forEach((node,i)=>{node.className="slot-symbol spinning";node.style.setProperty("--delay",`${(i%5)*90}ms`);node.innerHTML=`<b>${SLOT_SYMBOLS[i%SLOT_SYMBOLS.length].label}</b><span>NOIR</span>`;});
  await wait(880);const symbols=Array.from({length:3},(_,row)=>grid.map(column=>column[row])).flat();for(let column=0;column<5;column++){if(column===4&&anticipation){document.querySelector(".slot-stage").classList.add("anticipation");document.querySelector("#gameMessage").textContent="DOS DISPERSIONES · ÚLTIMO RODILLO";experience.audio.play("anticipacion");await wait(650);}await wait(135);experience.audio.play("stop");symbols.forEach((symbol,i)=>{if(i%5!==column)return;nodes[i].className="slot-symbol "+symbol.id.toLowerCase()+" reel-stop";nodes[i].innerHTML=`<b>${symbol.label}</b><span>${symbolName(symbol.id)}</span>`;});}
  if(outcome.freeSpins){current.freeSpins+=outcome.freeSpins;current.notifications.unshift({id:crypto.randomUUID(),title:"GIROS GRATIS DESBLOQUEADOS",body:`${outcome.freeSpins} giros acreditados.`,read:false});experience.audio.play("dispersion");}
  if(free) round.bet=0; engine.settleRound(current,round,outcome.payout,{scatters:outcome.scatters,freeSpinsAwarded:outcome.freeSpins});
  const multiplier=outcome.payout/Math.max(1,amount);document.querySelector("#gameMessage").textContent=outcome.payout?`${winTitle(multiplier)} · ${money(outcome.payout)}`:"SIN PREMIO · LA MÁQUINA TE ESPERA";experience.animateNumber(document.querySelector("#slotWin"),outcome.payout,"Gs. ");document.querySelector("#freeSpinCount").textContent=current.freeSpins;button.disabled=false;document.querySelector(".slot-stage").classList.remove("machine-active","anticipation");refreshHeader();
  if(outcome.wins.length){outcome.wins[0].line.forEach((row,column)=>nodes[row*5+column]?.classList.add("winner"));experience.winCelebration(outcome.payout,multiplier);}
}

const symbolName=(id)=>({TEN:"DIEZ",J:"J",Q:"Q",K:"K",A:"A",BAR:"BAR",BELL:"CAMPANA",DIAMOND:"DIAMANTE",SEVEN:"SIETE",WILD:"COMODÍN",SCATTER:"DISPERSIÓN"})[id]||id;

function bindRoulette() {
  const variant=db.data.games.roulette.variant||"european";
  rouletteRenderer=new RouletteWheelRenderer(document.querySelector("#rouletteCanvas"),{variant,quality:experience.ambient.quality(),audio:experience.audio});
  document.querySelectorAll("[data-chip]").forEach(button=>button.onclick=()=>{selectedRouletteChip=Number(button.dataset.chip);document.querySelectorAll("[data-chip]").forEach(item=>item.classList.toggle("active",item===button));experience.audio.play("chip");});
  document.querySelectorAll("[data-board-type]").forEach(button=>button.onclick=()=>addRouletteBet(button.dataset.boardType,button.dataset.boardTarget,selectedRouletteChip));
  document.querySelector("#rouletteAdd").onclick=()=>addRouletteBet(document.querySelector("#rouletteType").value,document.querySelector("#rouletteTarget").value,selectedRouletteChip);
  document.querySelector("#rouletteClear").onclick=()=>{rouletteBets=[];updateRouletteSlip();};
  document.querySelector("#rouletteSpin").onclick=playRoulette;
  bindRouletteSlipRemovers();
}

function addRouletteBet(type,target,amount){
  const variant=db.data.games.roulette.variant||"european";
  try{validateRouletteBet(type,target,variant);}catch(error){return toast("APUESTA INVÁLIDA",error.message,true);}
  const total=rouletteBets.reduce((sum,bet)=>sum+bet.amount,0)+amount;
  if(total>user().balance||total>db.data.games.roulette.maxBet)return toast("LÍMITE ALCANZADO","El total supera tu saldo o el máximo de la mesa.",true);
  const existing=rouletteBets.find((bet)=>bet.type===type&&String(bet.target)===String(target));
  if(existing)existing.amount+=amount;else rouletteBets.push({type,target,amount});
  experience.audio.play("chip");updateRouletteSlip();
}

function updateRouletteSlip(){
  const container=document.querySelector("#rouletteSlip"),stake=document.querySelector("#rouletteStake"),spin=document.querySelector("#rouletteSpin");
  if(container)container.innerHTML=rouletteSlipHtml();
  if(stake)experience.animateNumber(stake,rouletteBets.reduce((sum,bet)=>sum+bet.amount,0),"Gs. ");
  if(spin)spin.disabled=!rouletteBets.length;
  bindRouletteSlipRemovers();
}

function bindRouletteSlipRemovers(){document.querySelectorAll("[data-remove-bet]").forEach(button=>button.onclick=()=>{rouletteBets.splice(Number(button.dataset.removeBet),1);updateRouletteSlip();});}

async function playRoulette() {
  const variant=db.data.games.roulette.variant||"european",bets=rouletteBets.map((bet)=>({...bet})),amount=bets.reduce((sum,bet)=>sum+bet.amount,0),button=document.querySelector("#rouletteSpin");
  if(!amount)return;
  let round;
  try{bets.forEach((bet)=>validateRouletteBet(bet.type,bet.target,variant));round=engine.beginRound(user(),"roulette",amount,{variant,bets});}catch(error){return toast("NO SE PUDO APOSTAR",error.message,true);}
  // El resultado se genera y fija antes de cualquier cuadro de animación.
  const number=spinRoulette(variant);round.metadata.winningNumber=number;db.save();refreshHeader();
  button.disabled=true;document.querySelector(".roulette-wheel-wrap").classList.remove("winner-focus");document.querySelectorAll(".winning-number").forEach(cell=>cell.classList.remove("winning-number"));document.querySelector("#rouletteBoard").classList.add("bets-closed");document.querySelector("#rouletteHistory").textContent="APUESTAS CERRADAS · LA BOLA ESTÁ EN MOVIMIENTO";experience.audio.play("ruletaInicia");
  await rouletteRenderer.spinTo(number,{reduced:db.data.settings.motion!=="full"});
  const settlement=settleRouletteBets(bets,number,variant);engine.settleRound(user(),round,settlement.payout,{number,color:rouletteColor(number),winningBets:settlement.winners});
  const result=document.querySelector("#rouletteResult");result.textContent=number;result.className=rouletteColor(number);document.querySelector(".roulette-wheel-wrap").classList.add("winner-focus");
  document.querySelectorAll(`[data-board-target="${number}"]`).forEach(cell=>cell.classList.add("winning-number"));
  document.querySelector("#rouletteHistory").textContent=`RESULTADO · ${number} ${colorLabel(rouletteColor(number))} · ${settlement.payout?"PREMIO "+money(settlement.payout):"SIN PREMIO"}`;
  rouletteBets=[];updateRouletteSlip();document.querySelector("#rouletteBoard").classList.remove("bets-closed");button.disabled=true;refreshHeader();if(settlement.payout)experience.winCelebration(settlement.payout,settlement.payout/amount);else experience.audio.play("perdida");
}

const colorLabel=(color)=>({red:"ROJO",black:"NEGRO",green:"VERDE"})[color];

function bindBlackjack() {
  document.querySelectorAll("[data-blackjack-chip]").forEach(button=>button.onclick=()=>{document.querySelector("#gameBet").value=button.dataset.blackjackChip;document.querySelectorAll("[data-blackjack-chip]").forEach(item=>item.classList.toggle("active",item===button));button.classList.add("chip-flying");experience.audio.play("chip");setTimeout(()=>button.classList.remove("chip-flying"),500);});
  document.querySelector("#blackjackDeal").onclick=dealBlackjack;document.querySelector("#blackjackHit").onclick=()=>{experience.audio.play("card");blackjack.hit();updateBlackjack();};document.querySelector("#blackjackStand").onclick=()=>{blackjack.stand();updateBlackjack();};document.querySelector("#blackjackDouble").onclick=()=>{try{engine.addStake(user(),blackjackRound,blackjack.hand().bet);experience.audio.play("chip");blackjack.double();updateBlackjack();}catch(e){toast("DUPLICACIÓN RECHAZADA",e.message,true);}};document.querySelector("#blackjackSplit").onclick=()=>{try{engine.addStake(user(),blackjackRound,blackjack.hand().bet);blackjackRound.metadata.split=true;experience.audio.play("chip");blackjack.split();updateBlackjack();}catch(e){toast("DIVISIÓN RECHAZADA",e.message,true);}};document.querySelector("#blackjackInsurance").onclick=()=>{const stake=blackjack.hand().bet/2;try{engine.addStake(user(),blackjackRound,stake);blackjack.insurance=stake;experience.audio.play("chip");updateBlackjack();}catch(e){toast("SEGURO RECHAZADO",e.message,true);}};
}

function dealBlackjack() {
  const amount=Number(document.querySelector("#gameBet").value);try{blackjackRound=engine.beginRound(user(),"blackjack",amount);blackjack=new BlackjackTable(amount);}catch(e){return toast("NO SE PUDO REPARTIR",e.message,true);}experience.audio.play("chip");document.querySelector("#blackjackDeal").disabled=true;setTimeout(()=>experience.audio.play("card"),80);setTimeout(()=>experience.audio.play("card"),220);setTimeout(()=>experience.audio.play("card"),360);updateBlackjack();const player=scoreHand(blackjack.hand().cards),dealer=scoreHand(blackjack.dealer);if(player.blackjack||dealer.blackjack){blackjack.playDealer();updateBlackjack();}
}

function updateBlackjack() {
  const hand=blackjack?.hand(); if(!hand)return; const playerScore=scoreHand(hand.cards);
  document.querySelector("#playerCards").innerHTML=blackjack.hands.map((item,index)=>`<div class="hand ${index===blackjack.active?"active":""}">${item.cards.map(cardHtml).join("")}<small>MANO ${index+1} · ${scoreHand(item.cards).total}</small></div>`).join("");
  document.querySelector("#dealerCards").innerHTML=blackjack.dealer.map((card,index)=>!blackjack.complete&&index===1?`<i class="card back-card">N</i>`:cardHtml(card)).join("");document.querySelector("#playerScore").textContent=playerScore.total;document.querySelector("#dealerScore").textContent=blackjack.complete?scoreHand(blackjack.dealer).total:"";
  ["Hit","Stand"].forEach(id=>document.querySelector("#blackjack"+id).disabled=blackjack.complete);document.querySelector("#blackjackDouble").disabled=blackjack.complete||!blackjack.canDouble()||user().balance<hand.bet;document.querySelector("#blackjackSplit").disabled=blackjack.complete||!blackjack.canSplit()||user().balance<hand.bet;document.querySelector("#blackjackInsurance").disabled=blackjack.complete||!blackjack.canInsure()||user().balance<hand.bet/2;
  if(blackjack.complete){const settlement=blackjack.settle();engine.settleRound(user(),blackjackRound,settlement.payout,{results:settlement.results,dealerScore:settlement.dealerScore});document.querySelector("#gameMessage").textContent=settlement.results.map((r,i)=>`MANO ${i+1}: ${blackjackOutcome(r.outcome)}`).join(" · ");document.querySelector("#blackjackDeal").disabled=false;["Hit","Stand","Double","Split","Insurance"].forEach(id=>document.querySelector("#blackjack"+id).disabled=true);refreshHeader();if(settlement.payout>blackjackRound.bet)experience.winCelebration(settlement.payout,settlement.payout/blackjackRound.bet);else experience.audio.play("perdida");}
}

const blackjackOutcome=(outcome)=>({BLACKJACK:"BLACKJACK",WIN:"GANASTE",LOSE:"PERDISTE",PUSH:"EMPATE",BUST:"TE PASASTE","DEALER BLACKJACK":"BLACKJACK DEL CRUPIER"})[outcome]||String(outcome).toUpperCase();

function bindDice(){let type="under7";document.querySelectorAll("[data-dice-bet]").forEach(button=>button.onclick=()=>{type=button.dataset.diceBet;document.querySelectorAll("[data-dice-bet]").forEach(item=>item.classList.toggle("active",item===button));experience.audio.play("chip");});document.querySelector("#diceRoll").onclick=async()=>{const amount=Number(document.querySelector("#gameBet").value),button=document.querySelector("#diceRoll");let round;try{round=engine.beginRound(user(),"dice",amount,{type});}catch(error){return toast("NO SE PUDO APOSTAR",error.message,true);}const dice=rollDice(),payout=resolveDiceBet(type,amount,dice);refreshHeader();button.disabled=true;document.querySelector("#diceStage").classList.add("rolling");experience.audio.play("dados");await wait(1250);document.querySelectorAll(".die").forEach((die,index)=>die.dataset.face=dice[index]);document.querySelector("#diceStage").classList.remove("rolling");document.querySelector("#diceStage").classList.add("landed");document.querySelector("#diceTotal").textContent=dice[0]+dice[1];engine.settleRound(user(),round,payout,{dice,total:dice[0]+dice[1],type});document.querySelector("#gameMessage").textContent=payout?`GANANCIA · ${money(payout)}`:`RESULTADO ${dice[0]+dice[1]} · SIN PREMIO`;button.disabled=false;refreshHeader();if(payout)experience.winCelebration(payout,payout/amount);else experience.audio.play("perdida");};}

function bindBaccarat(){let type="player";document.querySelectorAll("[data-baccarat-bet]").forEach(button=>button.onclick=()=>{type=button.dataset.baccaratBet;document.querySelectorAll("[data-baccarat-bet]").forEach(item=>item.classList.toggle("active",item===button));experience.audio.play("chip");});document.querySelector("#baccaratDeal").onclick=async()=>{const amount=Number(document.querySelector("#gameBet").value),button=document.querySelector("#baccaratDeal"),table=document.querySelector(".baccarat-table");let round;try{round=engine.beginRound(user(),"baccarat",amount,{type});}catch(error){return toast("NO SE PUDO APOSTAR",error.message,true);}const result=baccaratRound(),payout=resolveBaccaratBet(type,amount,result);button.disabled=true;refreshHeader();delete table.dataset.winner;table.classList.remove("dealing");requestAnimationFrame(()=>table.classList.add("dealing"));for(let index=0;index<4;index+=1){experience.audio.play("card");await wait(190);}document.querySelector("#baccaratPlayer").innerHTML=result.player.map(cardHtml).join("");document.querySelector("#baccaratBanker").innerHTML=result.banker.map(cardHtml).join("");document.querySelector("#baccaratPlayerScore").textContent=result.playerScore;document.querySelector("#baccaratBankerScore").textContent=result.bankerScore;table.dataset.winner=result.winner;table.classList.remove("dealing");engine.settleRound(user(),round,payout,{...result,type});const winner={player:"JUGADOR",banker:"BANCA",tie:"EMPATE"}[result.winner];document.querySelector("#gameMessage").textContent=`GANA ${winner} · ${payout?"PREMIO "+money(payout):"SIN PREMIO"}`;button.disabled=false;refreshHeader();if(payout)experience.winCelebration(payout,payout/amount);else experience.audio.play("perdida");};}

function bindMines(){document.querySelector("#minesStart").onclick=()=>{if(minesRound&&!minesRound.complete)return;const amount=Number(document.querySelector("#gameBet").value);let round;try{round=engine.beginRound(user(),"mines",amount,{mineCount:3});}catch(error){return toast("NO SE PUDO INICIAR",error.message,true);}minesRound={round,mines:createMinesBoard(),revealed:new Set(),complete:false,multiplier:1};document.querySelectorAll("[data-mine-cell]").forEach(cell=>{cell.disabled=false;cell.className="";cell.innerHTML="<i></i><span></span>";});document.querySelector("#minesStart").disabled=true;document.querySelector("#minesCashout").disabled=true;document.querySelector("#gameMessage").textContent="ELEGÍ UNA CÁMARA";refreshHeader();};document.querySelectorAll("[data-mine-cell]").forEach(cell=>cell.onclick=()=>revealMineCell(Number(cell.dataset.mineCell),cell));document.querySelector("#minesCashout").onclick=cashoutMines;}

function revealMineCell(index,cell){if(!minesRound||minesRound.complete||minesRound.revealed.has(index))return;minesRound.revealed.add(index);cell.disabled=true;if(minesRound.mines.has(index)){cell.classList.add("mine-hit");cell.innerHTML="<i></i><span>×</span>";experience.audio.play("mina");minesRound.complete=true;engine.settleRound(user(),minesRound.round,0,{revealed:[...minesRound.revealed],mine:true});document.querySelector("#gameMessage").textContent="MINA ENCONTRADA · RONDA TERMINADA";revealAllMines();finishMinesControls();refreshHeader();return;}cell.classList.add("gem-found");cell.innerHTML="<i></i><span>◆</span>";experience.audio.play("gema");minesRound.multiplier=minesMultiplier(minesRound.revealed.size);document.querySelector("#minesMultiplier").textContent=minesRound.multiplier.toFixed(2)+"×";document.querySelector("#minesCashout").disabled=false;document.querySelector("#gameMessage").textContent=`GEMA ENCONTRADA · RETIRO ${money(minesRound.round.bet*minesRound.multiplier)}`;}

function revealAllMines(){document.querySelectorAll("[data-mine-cell]").forEach(cell=>{if(minesRound.mines.has(Number(cell.dataset.mineCell)))cell.classList.add("mine-reveal");cell.disabled=true;});}
function finishMinesControls(){document.querySelector("#minesStart").disabled=false;document.querySelector("#minesCashout").disabled=true;}
function cashoutMines(){if(!minesRound||minesRound.complete||!minesRound.revealed.size)return;minesRound.complete=true;const payout=Math.round(minesRound.round.bet*minesRound.multiplier);engine.settleRound(user(),minesRound.round,payout,{revealed:[...minesRound.revealed],multiplier:minesRound.multiplier});document.querySelector("#gameMessage").textContent=`RETIRO COMPLETADO · ${money(payout)}`;revealAllMines();finishMinesControls();refreshHeader();experience.winCelebration(payout,payout/minesRound.round.bet);}

function bindCrash(){document.querySelector("#crashStart").onclick=startCrash;document.querySelector("#crashCashout").onclick=cashoutCrash;drawCrashGraph(0,1);}
function startCrash(){if(crashRound&&!crashRound.complete)return;const amount=Number(document.querySelector("#gameBet").value);let round;try{round=engine.beginRound(user(),"crash",amount);}catch(error){return toast("NO SE PUDO INICIAR",error.message,true);}crashRound={round,crashPoint:generateCrashPoint(),multiplier:1,complete:false,start:performance.now()};document.querySelector("#crashStart").disabled=true;document.querySelector("#crashCashout").disabled=false;document.querySelector("#crashStatus").textContent="EN VUELO";document.querySelector(".crash-arena").classList.remove("crashed");document.querySelector(".crash-arena").classList.add("in-flight");experience.audio.play("crashInicia");refreshHeader();requestAnimationFrame(updateCrash);}
function updateCrash(now){if(!crashRound||crashRound.complete)return;const elapsed=(now-crashRound.start)/1000;crashRound.multiplier=Math.floor(Math.exp(elapsed*.23)*100)/100;document.querySelector("#crashMultiplier").textContent=crashRound.multiplier.toFixed(2)+"×";drawCrashGraph(Math.min(1,elapsed/12),crashRound.multiplier);if(crashRound.multiplier>=crashRound.crashPoint){crashRound.complete=true;engine.settleRound(user(),crashRound.round,0,{crashPoint:crashRound.crashPoint});document.querySelector("#crashStatus").textContent=`IMPACTO EN ${crashRound.crashPoint.toFixed(2)}×`;document.querySelector("#gameMessage").textContent="LA RONDA TERMINÓ";document.querySelector(".crash-arena").classList.remove("in-flight");document.querySelector(".crash-arena").classList.add("crashed");document.querySelector("#crashStart").disabled=false;document.querySelector("#crashCashout").disabled=true;experience.audio.play("crash");refreshHeader();return;}requestAnimationFrame(updateCrash);}
function cashoutCrash(){if(!crashRound||crashRound.complete)return;crashRound.complete=true;const payout=Math.round(crashRound.round.bet*crashRound.multiplier);engine.settleRound(user(),crashRound.round,payout,{cashout:crashRound.multiplier,crashPoint:crashRound.crashPoint});document.querySelector("#crashStatus").textContent=`RETIRADO EN ${crashRound.multiplier.toFixed(2)}×`;document.querySelector("#gameMessage").textContent=`GANANCIA · ${money(payout)}`;document.querySelector("#crashStart").disabled=false;document.querySelector("#crashCashout").disabled=true;document.querySelector(".crash-arena").classList.remove("in-flight");refreshHeader();experience.winCelebration(payout,crashRound.multiplier);}
function drawCrashGraph(progress,multiplier){const canvas=document.querySelector("#crashCanvas");if(!canvas)return;const bounds=canvas.getBoundingClientRect(),ratio=Math.min(devicePixelRatio,1.5);canvas.width=bounds.width*ratio;canvas.height=bounds.height*ratio;const ctx=canvas.getContext("2d");ctx.scale(ratio,ratio);const width=bounds.width,height=bounds.height;ctx.clearRect(0,0,width,height);ctx.strokeStyle="rgba(255,255,255,.08)";ctx.lineWidth=1;for(let i=1;i<6;i++){ctx.beginPath();ctx.moveTo(0,height*i/6);ctx.lineTo(width,height*i/6);ctx.stroke();}const endX=width*(.12+progress*.76),endY=height*.82-Math.min(height*.68,Math.log(multiplier)*height*.24);const gradient=ctx.createLinearGradient(0,height,endX,endY);gradient.addColorStop(0,"#ff512f");gradient.addColorStop(.55,"#ff1f70");gradient.addColorStop(1,"#ffd35a");ctx.strokeStyle=gradient;ctx.lineWidth=5;ctx.shadowBlur=18;ctx.shadowColor="#ff286f";ctx.beginPath();ctx.moveTo(width*.08,height*.84);ctx.quadraticCurveTo(endX*.6,height*.8,endX,endY);ctx.stroke();ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(endX,endY,6,0,Math.PI*2);ctx.fill();}

const cardHtml=card=>`<i class="card ${["♥","♦"].includes(card.suit)?"red-card":""}"><b>${card.rank}</b><span>${card.suit}</span></i>`;
const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const winTitle=m=>m>=500?"PREMIO LEGENDARIO":m>=100?"PREMIO ÉPICO":m>=50?"PREMIO MEGA":m>=20?"GRAN PREMIO":"GANANCIA";

function renderProfile() {
  const current=user(),favorite=GAMES.find(game=>game.id===current.favorites[0]);
  app.innerHTML=shell(`<section class="profile-page"><header class="profile-hero"><div class="avatar-large">${escapeHtml(current.avatar)}</div><div><p class="overline">MIEMBRO NOIR DESDE ${new Date(current.createdAt).getFullYear()}</p><h1>${escapeHtml(current.username)}</h1><span>${rankLabel(current.rank)} · NIVEL ${current.level}</span></div><button id="editAvatar" class="light-button">CAMBIAR AVATAR</button></header><div class="profile-stats">${[["SALDO",money(current.balance)],["TOTAL APOSTADO",money(current.stats.totalWagered)],["TOTAL GANADO",money(current.stats.totalWon)],["MAYOR GANANCIA",money(current.stats.biggestWin)],["RONDAS JUGADAS",current.stats.gamesPlayed],["FAVORITO",favorite?.name||"—"]].map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong></article>`).join("")}</div><section class="activity"><header><div><p class="overline">REGISTRO DE RONDAS</p><h2>MI ACTIVIDAD</h2></div></header><div class="activity-table"><div class="activity-row heading"><span>FECHA</span><span>JUEGO</span><span>APUESTA</span><span>MULT.</span><span>RESULTADO</span></div>${current.history.length?current.history.map(round=>`<div class="activity-row"><span>${new Date(round.createdAt).toLocaleString("es-PY",{dateStyle:"short",timeStyle:"short"})}</span><span>${GAMES.find(game=>game.id===round.game)?.name||round.game}</span><span>${money(round.bet)}</span><span>${round.multiplier.toFixed(2)}x</span><strong class="${round.net>=0?"positive":"negative"}">${round.net>=0?"+":""}${money(round.net)}</strong></div>`).join(""):`<div class="empty-state"><i>N</i><b>TU PRIMERA RONDA TE ESPERA</b><span>Elegí un juego para iniciar tu historial privado.</span><button data-go="/lobby">IR A LA SALA</button></div>`}</div></section></section>`,"profile");bindShell();document.querySelector("#editAvatar").onclick=()=>{const value=prompt("Iniciales del avatar (máximo 2)",current.avatar);if(value){current.avatar=value.slice(0,2).toUpperCase();db.save();renderProfile();}};
}

function renderAdmin() {
  if(!db.data.adminSession){app.innerHTML=`<main class="admin-login"><a class="wordmark" href="#/">NOIR<span>ADMIN</span></a><form id="adminForm"><p class="overline">CENTRO DE CONTROL LOCAL</p><h1>ACCESO ADMINISTRATIVO</h1><label>Código local<input type="password" name="code" required></label><button class="gold-button">ENTRAR</button><small>Demostración local: NOIR-LOCAL-ADMIN</small></form></main>`;document.querySelector("#adminForm").onsubmit=e=>{e.preventDefault();if(new FormData(e.currentTarget).get("code")!=="NOIR-LOCAL-ADMIN")return toast("ACCESO DENEGADO","Código administrativo inválido.",true);db.data.adminSession=true;db.addAudit("INICIO_ADMIN");db.save();renderAdmin();};return;}
  const aggregate=db.data.users.reduce((a,u)=>({balance:a.balance+u.balance,wagered:a.wagered+u.stats.totalWagered,paid:a.paid+u.stats.totalWon,rounds:a.rounds+u.stats.gamesPlayed}),{balance:0,wagered:0,paid:0,rounds:0});
  const rouletteStats=db.data.users.reduce((stats,item)=>{const game=item.stats.byGame.roulette||{};stats.rounds+=game.rounds||0;stats.wagered+=game.wagered||0;stats.paid+=game.paid||0;return stats;},{rounds:0,wagered:0,paid:0});
  const variant=db.data.games.roulette.variant||"european",rouletteTheory=theoreticalRouletteMetrics(variant),observedRtp=rouletteStats.wagered?rouletteStats.paid/rouletteStats.wagered:0;
  app.innerHTML=`<div class="admin-shell"><aside><a class="wordmark" href="#/admin">NOIR<span>CONTROL</span></a><button class="active" data-admin-tab="top">RESUMEN</button><button data-admin-tab="adminUsers">USUARIOS</button><button data-admin-tab="adminGames">JUEGOS</button><button data-admin-tab="rouletteLab">LABORATORIO</button><button data-admin-tab="adminAudit">AUDITORÍA</button><div></div><button data-go="/lobby">← CASINO</button><button id="adminLogout">CERRAR SESIÓN</button></aside><main id="top"><header><div><p class="overline">CONTROL DE SIMULACIÓN</p><h1>RESUMEN DE OPERACIONES</h1></div><span>${new Date().toLocaleString("es-PY")}</span></header><div class="admin-metrics">${[["USUARIOS LOCALES",db.data.users.length],["SALDO VIRTUAL TOTAL",money(aggregate.balance)],["TOTAL APOSTADO",money(aggregate.wagered)],["TOTAL PAGADO",money(aggregate.paid)],["RTP OBSERVADO",aggregate.wagered?(aggregate.paid/aggregate.wagered*100).toFixed(2).replace(".",",")+"%":"—"],["RONDAS JUGADAS",aggregate.rounds]].map(([l,v])=>`<article><span>${l}</span><strong>${v}</strong></article>`).join("")}</div>
  <section class="admin-section" id="adminGames"><header><h2>CONFIGURACIÓN DE JUEGOS</h2><span>Todos los importes son guaraníes virtuales</span></header><div class="admin-games">${Object.entries(db.data.games).map(([id,c])=>`<article><div><b>${c.name}</b><span>${id==="slot"?`RTP teórico ${(theoreticalSlotRtp()*100).toFixed(2).replace(".",",")}%`:id==="roulette"?`RTP teórico ${(rouletteTheory.rtp*100).toFixed(2).replace(".",",")}% · ventaja ${(rouletteTheory.houseEdge*100).toFixed(2).replace(".",",")}%`:"Reglas matemáticas propias"}</span></div><label>APUESTA MÍNIMA<input data-config="${id}:minBet" type="number" value="${c.minBet}"></label><label>APUESTA MÁXIMA<input data-config="${id}:maxBet" type="number" value="${c.maxBet}"></label><label class="switch"><input data-config="${id}:enabled" type="checkbox" ${c.enabled?"checked":""}><i></i>ACTIVO</label></article>`).join("")}</div><div class="roulette-variant-config"><label>TIPO DE RULETA<select data-config="roulette:variant"><option value="european" ${variant==="european"?"selected":""}>Europea · 37 casillas · 2,70 %</option><option value="american" ${variant==="american"?"selected":""}>Americana · 38 casillas · 5,26 %</option></select></label><p>La variante modifica únicamente la cantidad de casillas. Los pagos estándar permanecen visibles y nunca se alteran silenciosamente.</p></div><button id="saveConfig" class="gold-button">GUARDAR CONFIGURACIÓN</button></section>
  <section class="admin-section roulette-lab" id="rouletteLab"><header><div><p class="overline">AUDITORÍA MATEMÁTICA</p><h2>SIMULADOR DE RULETA</h2></div><span>RNG uniforme · sin ajustes por usuario</span></header><div class="roulette-admin-metrics">${[["VARIANTE",ROULETTE_VARIANTS[variant].label],["RTP TEÓRICO",(rouletteTheory.rtp*100).toFixed(4)+"%"],["VENTAJA TEÓRICA",(rouletteTheory.houseEdge*100).toFixed(4)+"%"],["RTP OBSERVADO",rouletteStats.rounds?(observedRtp*100).toFixed(4)+"%":"—"],["RONDAS REALES",rouletteStats.rounds],["TOTAL APOSTADO",money(rouletteStats.wagered)],["TOTAL PAGADO",money(rouletteStats.paid)],["RESULTADO DEL CASINO",money(rouletteStats.wagered-rouletteStats.paid)],["BENEFICIO TEÓRICO",money(rouletteStats.wagered*rouletteTheory.houseEdge)]].map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong></article>`).join("")}</div><div class="simulation-actions"><button data-simulate="10000">SIMULAR 10.000</button><button data-simulate="100000">SIMULAR 100.000</button><button data-simulate="1000000">SIMULAR 1.000.000</button></div><div class="simulation-progress"><i id="simulationProgress"></i><span id="simulationStatus">LISTO PARA SIMULAR</span></div><div id="simulationResults" class="simulation-results"><p>Los resultados mostrarán frecuencias, RTP, ventaja y beneficio virtual.</p></div></section>
  <section class="admin-section" id="adminUsers"><header><h2>USUARIOS LOCALES</h2><span>Los cambios se registran en auditoría</span></header>${db.data.users.map(u=>`<div class="admin-user"><i>${escapeHtml(u.avatar)}</i><span><b>${escapeHtml(u.username)}</b><small>${escapeHtml(u.email)}</small></span><strong>${money(u.balance)}</strong><button data-credit="${u.id}">+ Gs. 100.000</button></div>`).join("")||"Todavía no hay usuarios."}</section><section class="admin-section" id="adminAudit"><header><h2>REGISTRO DE AUDITORÍA</h2></header>${db.data.audit.slice(0,10).map(log=>`<div class="audit-row"><span>${new Date(log.date).toLocaleString("es-PY")}</span><b>${log.action}</b><span>${log.target}</span></div>`).join("")||"Todavía no hay acciones."}</section></main></div>`;
  bindCommon();document.querySelector("#adminLogout").onclick=()=>{db.data.adminSession=false;db.save();renderAdmin();};document.querySelector("#saveConfig").onclick=saveAdminConfig;document.querySelectorAll("[data-credit]").forEach(button=>button.onclick=()=>adminCredit(button.dataset.credit));document.querySelectorAll("[data-admin-tab]").forEach(button=>button.onclick=()=>document.querySelector("#"+button.dataset.adminTab)?.scrollIntoView({behavior:"smooth"}));document.querySelectorAll("[data-simulate]").forEach(button=>button.onclick=()=>runAdminSimulation(Number(button.dataset.simulate)));
}

function saveAdminConfig(){document.querySelectorAll("[data-config]").forEach(input=>{const[id,key]=input.dataset.config.split(":"),old=db.data.games[id][key],value=input.type==="checkbox"?input.checked:input.tagName==="SELECT"?input.value:Number(input.value);db.data.games[id][key]=value;if(old!==value)db.addAudit("CONFIGURACIÓN_CAMBIADA",old,value,id+":"+key);});db.save();toast("CONFIGURACIÓN GUARDADA","Los cambios se aplican a la próxima ronda.");renderAdmin();}
function adminCredit(id){const target=db.data.users.find(u=>u.id===id),old=target.balance;target.balance+=100000;db.addAudit("SALDO_VIRTUAL_AÑADIDO",old,target.balance,target.username);db.save();renderAdmin();}

async function runAdminSimulation(rounds){const buttons=[...document.querySelectorAll("[data-simulate]")],progress=document.querySelector("#simulationProgress"),status=document.querySelector("#simulationStatus"),results=document.querySelector("#simulationResults"),variant=db.data.games.roulette.variant||"european";buttons.forEach(button=>button.disabled=true);status.textContent=`SIMULANDO ${rounds.toLocaleString("es-PY")} RONDAS…`;const simulation=await simulateRouletteAsync(rounds,variant,value=>{progress.style.width=(value*100).toFixed(1)+"%";status.textContent=`PROGRESO ${(value*100).toFixed(0)} %`;});const theory=theoreticalRouletteMetrics(variant),expected=rounds/theory.pockets,maxDeviation=Math.max(...Object.values(simulation.frequency).map(count=>Math.abs(count-expected)/expected));results.innerHTML=`<div class="simulation-summary">${[["RONDAS",simulation.rounds.toLocaleString("es-PY")],["RTP OBSERVADO",(simulation.rtp*100).toFixed(4)+"%"],["RTP TEÓRICO",(theory.rtp*100).toFixed(4)+"%"],["VENTAJA OBSERVADA",(simulation.houseEdge*100).toFixed(4)+"%"],["VENTAJA TEÓRICA",(theory.houseEdge*100).toFixed(4)+"%"],["BENEFICIO VIRTUAL",simulation.profit.toLocaleString("es-PY")],["DESVIACIÓN MÁXIMA",(maxDeviation*100).toFixed(2)+"%"]].map(([label,value])=>`<article><span>${label}</span><strong>${value}</strong></article>`).join("")}</div><div class="frequency-chart">${Object.entries(simulation.frequency).map(([number,count])=>`<i class="${rouletteColor(number)}" style="--frequency:${count/expected}"><b>${number}</b><span>${count.toLocaleString("es-PY")}</span></i>`).join("")}</div><div class="simulation-splits"><span>ROJO ${simulation.colors.red.toLocaleString("es-PY")}</span><span>NEGRO ${simulation.colors.black.toLocaleString("es-PY")}</span><span>VERDE ${simulation.colors.green.toLocaleString("es-PY")}</span><span>PAR ${simulation.parity.even.toLocaleString("es-PY")}</span><span>IMPAR ${simulation.parity.odd.toLocaleString("es-PY")}</span></div>`;status.textContent="SIMULACIÓN COMPLETADA";buttons.forEach(button=>button.disabled=false);db.addAudit("SIMULACIÓN_RULETA",null,{rounds,rtp:simulation.rtp,houseEdge:simulation.houseEdge},variant);db.save();}

function showWallet(){const current=user();modalRoot.innerHTML=`<div class="modal-backdrop"><section class="wallet-modal"><button class="modal-close">×</button><p class="overline">BILLETERA VIRTUAL</p><h2>${money(current.balance)}</h2><span class="virtual-stamp">SALDO VIRTUAL — SIN VALOR MONETARIO REAL</span><div>${[["GANANCIAS TOTALES",money(current.stats.totalWon)],["APUESTAS TOTALES",money(current.stats.totalWagered)],["SALDO DE BONIFICACIÓN",money(current.bonusBalance)],["PREMIOS MAYORES GANADOS",current.stats.jackpotsWon]].map(([l,v])=>`<article><span>${l}</span><strong>${v}</strong></article>`).join("")}</div><button class="gold-button" id="modalClaim">OBTENER CRÉDITOS DE PRUEBA</button></section></div>`;modalRoot.querySelector(".modal-close").onclick=closeModal;modalRoot.querySelector(".modal-backdrop").onclick=e=>{if(e.target===e.currentTarget)closeModal();};modalRoot.querySelector("#modalClaim").onclick=claimCredits;}
function showNotifications(){const current=user();current.notifications.forEach(n=>n.read=true);db.save();modalRoot.innerHTML=`<div class="modal-backdrop"><section class="notice-modal"><button class="modal-close">×</button><p class="overline">NOTIFICACIONES NOIR</p><h2>TUS EVENTOS</h2>${current.notifications.slice(0,10).map(n=>`<article><b>${escapeHtml(n.title)}</b><p>${escapeHtml(n.body)}</p></article>`).join("")||"<p>No hay notificaciones.</p>"}</section></div>`;modalRoot.querySelector(".modal-close").onclick=closeModal;}
function showPaytable(){modalRoot.innerHTML=`<div class="modal-backdrop"><section class="paytable-modal"><button class="modal-close">×</button><p class="overline">NOIR 777</p><h2>TABLA DE PAGOS</h2><div>${SLOT_SYMBOLS.map(s=>`<article><b>${s.label}</b><span>3 · ${(s.pay[2]*SLOT_PAYOUT_SCALE).toFixed(1)}x</span><span>4 · ${(s.pay[3]*SLOT_PAYOUT_SCALE).toFixed(1)}x</span><span>5 · ${(s.pay[4]*SLOT_PAYOUT_SCALE).toFixed(1)}x</span></article>`).join("")}</div><small>Premios de línea aplicados proporcionalmente sobre 20 líneas. La dispersión paga sobre la apuesta total.</small></section></div>`;modalRoot.querySelector(".modal-close").onclick=closeModal;}
function showRewards(){const current=user(),rewards=[25000,50000,5,100000,10,250000,500000],last=current.dailyReward?.lastClaimAt?Date.parse(current.dailyReward.lastClaimAt):0,available=Date.now()-last>=20*60*60*1000,day=(current.dailyReward?.streak||0)%7;modalRoot.innerHTML=`<div class="modal-backdrop vault-backdrop"><section class="reward-vault"><button class="modal-close">×</button><div class="vault-wheel"><i></i><b>N</b><span></span></div><p class="overline">BÓVEDA DIARIA</p><h2>SIETE NOCHES DE FORTUNA</h2><div class="reward-days">${rewards.map((value,index)=>`<article class="${index<day?"claimed":index===day?"current":""}"><span>NOCHE ${index+1}</span><div class="reward-chest"><i></i><b>${index===2||index===4?value+" GIROS":money(value)}</b></div></article>`).join("")}</div><button id="claimDaily" class="play-cta" ${available?"":"disabled"}><span>${available?"ABRIR LA BÓVEDA":"BÓVEDA RECARGANDO"}</span><b>→</b></button><small>${available?"Hay una recompensa virtual preparada.":"Volvé en la próxima noche del casino."}</small></section></div>`;modalRoot.querySelector(".modal-close").onclick=closeModal;modalRoot.querySelector("#claimDaily").onclick=()=>{if(!available)return;const reward=rewards[day];if(day===2||day===4)current.freeSpins+=reward;else current.balance+=reward;current.dailyReward={lastClaimAt:new Date().toISOString(),streak:day+1};current.notifications.unshift({id:crypto.randomUUID(),title:"BÓVEDA DIARIA ABIERTA",body:day===2||day===4?`${reward} giros gratis acreditados.`:`${money(reward)} acreditados.`,read:false});db.save();experience.audio.play("bigWin");closeModal();refreshHeader();experience.winCelebration(day===2||day===4?reward*10000:reward,25);};}
function closeModal(){modalRoot.innerHTML="";}

function claimCredits(){const current=user(),now=Date.now(),cooldown=12*60*60*1000,last=current.lastTestCreditAt?Date.parse(current.lastTestCreditAt):0;if(now-last<cooldown)return toast("CRÉDITOS NO DISPONIBLES",`Volvé en ${Math.ceil((cooldown-(now-last))/3600000)} hora(s).`,true);current.balance+=250000;current.lastTestCreditAt=new Date().toISOString();current.notifications.unshift({id:crypto.randomUUID(),title:"CRÉDITOS DE PRUEBA",body:`${money(250000)} acreditados.`,read:false});db.save();closeModal();refreshHeader();toast("CRÉDITOS ACREDITADOS",money(250000)+" virtuales.");}

function bindCommon(){document.querySelectorAll("[data-go]").forEach(button=>button.onclick=()=>{const [path,query]=button.dataset.go.split("?");if(query?.startsWith("cat="))lobbyCategory=query.slice(4);go(path);});document.querySelectorAll("[data-auth]").forEach(button=>button.onclick=()=>{authMode=button.dataset.auth;go("/auth");});}
function bindShell(){bindCommon();document.querySelector("#walletButton").onclick=showWallet;document.querySelector("#noticeButton").onclick=showNotifications;document.querySelector("#audioButton").onclick=()=>experience.openAudioPanel(modalRoot);document.querySelector("#rewardsButton").onclick=showRewards;document.querySelector("#mobileRewards")?.addEventListener("click",showRewards);document.querySelector("#logoutButton").onclick=()=>{db.data.sessionUserId=null;db.save();go("/");};document.querySelector("#adminLink").onclick=()=>go("/admin");}
function refreshHeader(){const pill=document.querySelector("#walletButton span");if(pill)experience.animateNumber(pill,user().balance,"Gs. ");}
function toast(title,body,error=false){experience.audio.play(error?"error":"click");const node=document.createElement("article");node.className="toast "+(error?"error":"");node.innerHTML=`<i></i><b>${escapeHtml(title)}</b><span>${escapeHtml(body)}</span>`;document.querySelector("#toastRoot").appendChild(node);setTimeout(()=>node.remove(),4200);}
function debugPanel(){const variant=db.data.games.roulette.variant||"european",metrics=theoreticalRouletteMetrics(variant);return `<details class="debug-panel"><summary>MODO DE DEPURACIÓN</summary><pre>RNG seguro: crypto.getRandomValues\nRTP teórico del slot: ${(theoreticalSlotRtp()*100).toFixed(4)}%\nruleta: ${ROULETTE_VARIANTS[variant].label}\nprobabilidad por casilla: 1 / ${metrics.pockets}\nRTP teórico de ruleta: ${(metrics.rtp*100).toFixed(4)}%\njuego actual: ${currentGame}\nid de usuario: ${user().id}</pre></details>`;}

window.addEventListener("hashchange",route);
window.addEventListener("keydown",event=>{if(event.key==="Escape")closeModal();});
route();
