(function(){"use strict";
var KEY="noir-casino-state-v1",BETS=[10,25,50,100,250];
var SYMBOLS=[{id:"NOIR",mark:"N",weight:4,pay:[0,0,8,20,70]},{id:"SEVEN",mark:"7",weight:6,pay:[0,0,6,15,55]},{id:"CROWN",mark:"♛",weight:9,pay:[0,0,5,10,35]},{id:"DIAMOND",mark:"◆",weight:13,pay:[0,0,4,8,20]},{id:"BAR",mark:"BAR",weight:18,pay:[0,0,3,6,14]},{id:"STAR",mark:"✦",weight:24,pay:[0,0,2,4,10]}];
var LINES=[[1,1,1,1,1],[0,0,0,0,0],[2,2,2,2,2],[0,1,2,1,0],[2,1,0,1,2],[0,0,1,2,2],[2,2,1,0,0],[1,0,0,0,1],[1,2,2,2,1],[0,1,1,1,0]];
var defaults={balance:10000,betIndex:0,lastWin:0,jackpot:2483710,muted:false},state=load(),spinning=false,scene="entrance",reels=[];
var entrance=document.getElementById("entrance"),lobby=document.getElementById("lobby"),game=document.getElementById("game"),windowEl=document.getElementById("reelWindow"),result=document.getElementById("result"),spinButton=document.getElementById("spin"),audio=createAudio();
function load(){try{var s=JSON.parse(localStorage.getItem(KEY));if(!s||typeof s.balance!=="number")return Object.assign({},defaults);return Object.assign({},defaults,s,{betIndex:Math.max(0,Math.min(BETS.length-1,s.betIndex||0))})}catch(e){return Object.assign({},defaults)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch(e){}}
function credits(n){return Math.max(0,Math.floor(n)).toLocaleString("en-US")+" CR"}
function randomSymbol(){var total=SYMBOLS.reduce(function(a,s){return a+s.weight},0),roll=Math.random()*total;for(var i=0;i<SYMBOLS.length;i++){roll-=SYMBOLS[i].weight;if(roll<=0)return SYMBOLS[i]}return SYMBOLS[5]}
function symbolNode(s,c,r){var n=document.createElement("div");n.className="symbol";n.dataset.symbol=s.id;n.dataset.col=c;n.dataset.row=r;n.textContent=s.mark;return n}
function renderReel(i,values){var reel=reels[i];reel.values=values;reel.element.innerHTML="";values.forEach(function(s,r){reel.element.appendChild(symbolNode(s,i,r))})}
function buildReels(){for(var c=0;c<5;c++){var el=document.createElement("div");el.className="reel";var values=[randomSymbol(),randomSymbol(),randomSymbol()];windowEl.appendChild(el);reels.push({element:el,values:values});renderReel(c,values)}}
function update(){var bet=BETS[state.betIndex];document.getElementById("balance").textContent=credits(state.balance);document.getElementById("balanceLobby").textContent=credits(state.balance);document.getElementById("jackpotLobby").textContent=credits(state.jackpot);document.getElementById("bet").textContent=credits(bet);document.getElementById("lastWin").textContent="LAST WIN "+credits(state.lastWin);document.getElementById("betDown").disabled=spinning||state.betIndex===0;document.getElementById("betUp").disabled=spinning||state.betIndex===BETS.length-1;spinButton.disabled=spinning||state.balance<bet;document.getElementById("sound").textContent=state.muted?"×":"♪";document.getElementById("sound").setAttribute("aria-pressed",String(state.muted));document.getElementById("sound").setAttribute("aria-label",state.muted?"Enable sound":"Mute sound")}
function show(name){[entrance,lobby,game].forEach(function(el){el.classList.remove("active")});(name==="entrance"?entrance:name==="lobby"?lobby:game).classList.add("active");scene=name}
function enter(){audio.unlock();audio.play("door");entrance.classList.add("opening");setTimeout(function(){show("lobby");entrance.classList.remove("opening")},1100)}
function openGame(){if(lobby.classList.contains("camera-in"))return;audio.unlock();audio.play("select");lobby.classList.add("camera-in");setTimeout(function(){show("game");lobby.classList.remove("camera-in");update()},920)}
function back(){if(spinning)return;audio.play("back");game.style.transform="scale(1.08)";game.style.opacity="0";setTimeout(function(){game.style.transform="";game.style.opacity="";show("lobby");update()},430)}
function setBet(d){if(spinning)return;var next=Math.max(0,Math.min(BETS.length-1,state.betIndex+d));if(next!==state.betIndex){state.betIndex=next;state.lastWin=0;audio.play("bet");save();update()}}
function clearWin(){game.classList.remove("has-win");result.classList.remove("won");windowEl.querySelectorAll(".symbol").forEach(function(n){n.classList.remove("win","dim")})}
function calculate(){var mult=0,cells=[];LINES.forEach(function(line){var first=reels[0].values[line[0]],count=1;for(var c=1;c<5;c++){if(reels[c].values[line[c]].id===first.id)count++;else break}if(count>=3){mult+=first.pay[count-1];for(var i=0;i<count;i++)cells.push(i+":"+line[i])}});return{amount:mult*BETS[state.betIndex],cells:Array.from(new Set(cells))}}
function finish(){var win=calculate();state.lastWin=win.amount;state.balance+=win.amount;if(win.amount>0){game.classList.add("has-win");result.classList.add("won");result.textContent="WIN  "+credits(win.amount);var set=new Set(win.cells);windowEl.querySelectorAll(".symbol").forEach(function(n){n.classList.add(set.has(n.dataset.col+":"+n.dataset.row)?"win":"dim")});audio.play("win")}else{result.textContent="NO WIN — THE HOUSE WAITS";audio.play("lose")}spinning=false;save();update()}
function spin(){var bet=BETS[state.betIndex];if(spinning||state.balance<bet)return;audio.unlock();clearWin();spinning=true;state.balance-=bet;state.lastWin=0;state.jackpot+=Math.max(1,Math.floor(bet*.03));result.textContent="REELS IN MOTION";spinButton.classList.add("pressed");setTimeout(function(){spinButton.classList.remove("pressed")},140);update();audio.play("spin");var timers=[];reels.forEach(function(reel,i){reel.element.classList.add("spinning");timers[i]=setInterval(function(){renderReel(i,[randomSymbol(),randomSymbol(),randomSymbol()]);reels[i].element.classList.add("spinning");audio.play("tick")},85+i*7);setTimeout(function(){clearInterval(timers[i]);renderReel(i,[randomSymbol(),randomSymbol(),randomSymbol()]);reels[i].element.classList.remove("spinning");audio.play("stop");if(i===4)setTimeout(finish,180)},900+i*245)})}
function particles(){var box=document.getElementById("particles");for(var i=0;i<28;i++){var p=document.createElement("i");p.className="particle";p.style.left=(8+Math.random()*84)+"%";p.style.top=(38+Math.random()*56)+"%";p.style.setProperty("--dur",(8+Math.random()*11)+"s");p.style.setProperty("--delay",(-Math.random()*16)+"s");p.style.setProperty("--alpha",(.12+Math.random()*.34).toFixed(2));p.style.setProperty("--drift",(-35+Math.random()*70)+"px");box.appendChild(p)}}
function createAudio(){var ctx=null,last=0;function unlock(){if(state.muted)return;if(!ctx)ctx=new(window.AudioContext||window.webkitAudioContext)();if(ctx.state==="suspended")ctx.resume()}function tone(f,d,type,v,delay){if(state.muted)return;unlock();if(!ctx)return;var now=ctx.currentTime+(delay||0),o=ctx.createOscillator(),g=ctx.createGain();o.type=type||"sine";o.frequency.setValueAtTime(f,now);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(v||.035,now+.012);g.gain.exponentialRampToValueAtTime(.0001,now+d);o.connect(g);g.connect(ctx.destination);o.start(now);o.stop(now+d+.03)}function play(n){if(state.muted)return;if(n==="tick"){var now=performance.now();if(now-last<65)return;last=now;tone(520,.045,"square",.008);return}if(n==="door"){tone(72,.8,"sine",.05);tone(108,.7,"triangle",.025,.15)}if(n==="select"){tone(220,.18,"triangle",.035);tone(330,.3,"sine",.025,.12)}if(n==="back")tone(175,.24,"triangle",.025);if(n==="bet")tone(620,.09,"sine",.025);if(n==="spin"){tone(92,.5,"sawtooth",.025);tone(138,.7,"triangle",.018)}if(n==="stop")tone(145,.11,"square",.028);if(n==="lose")tone(120,.28,"triangle",.018);if(n==="win")[262,330,392,523].forEach(function(f,i){tone(f,.5,"sine",.04,i*.11)})}return{unlock:unlock,play:play}}
document.getElementById("enter").addEventListener("click",enter);document.getElementById("openGame").addEventListener("click",openGame);document.getElementById("back").addEventListener("click",back);spinButton.addEventListener("click",spin);document.getElementById("betDown").addEventListener("click",function(){setBet(-1)});document.getElementById("betUp").addEventListener("click",function(){setBet(1)});document.getElementById("sound").addEventListener("click",function(){state.muted=!state.muted;if(!state.muted){audio.unlock();audio.play("bet")}save();update()});document.addEventListener("keydown",function(e){if(e.key==="Enter"&&scene==="entrance")enter();if(e.code==="Space"&&scene==="game"&&!e.repeat){e.preventDefault();spin()}if(e.key==="Escape"&&scene==="game")back()});lobby.addEventListener("pointermove",function(e){if(e.pointerType==="touch")return;var x=(e.clientX/innerWidth-.5)*2,y=(e.clientY/innerHeight-.5)*2;lobby.style.setProperty("--x",x.toFixed(3));lobby.style.setProperty("--y",y.toFixed(3))});lobby.addEventListener("pointerleave",function(){lobby.style.setProperty("--x",0);lobby.style.setProperty("--y",0)});setInterval(function(){if(scene==="lobby"&&!document.hidden){state.jackpot+=Math.floor(Math.random()*4)+1;update();save()}},3500);buildReels();particles();update();
})();
